### ISSUE TITLE
test in my  clsuter

### ISSUE THREAD

**Issue by suchisubhra** [fabric8io/kubernetes-zipkin#39]
I was able to deploy pipkin  in my  k8s cluster. I am trying to  find out how we can add tracing in my other containers ....our MSs are mostly go.

Also  i  am running minimal  pipkin  right now

**Comment by iocanel** [comment]
Hi! There are quite a few libraries out there that play nicely with zipkin. You can use this project to get zipkin running and then use one of those libraries so that you can integrate with zipkin.

I don't see this being in the scope of this project, so I am going to close this issue. If I missed somethign or if there is an other issue, please feel free to reopen or create a new one.
