### ISSUE TITLE
No name appears on the fabric8 console for the zipkin package.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-zipkin#65]
@jstrachan, @rawlingsj: any idea what might be missing?

**Comment by jstrachan** [comment]
you migrated to fmp 3? Got a sample yaml we can look at for the package?

**Comment by iocanel** [comment]
Yes, I migrated to f-m-p 3!

The package project doesn't contain anything, just aggregates existing stuff.

**Comment by jstrachan** [comment]
BTW I've been moving all the app catalog + packages here:
https://github.com/fabric8io/fabric8-platform/tree/master/packages

so that its easier to provide a consistent UX for installing everything from a single YAML or helm chart. Lemme try move the kubernetes-zipkin packages there and see if I can get it to appear nicely on the run menu
